version: '3.8'
services:
  gateway:
    build: .
    image: amazoncorretto:11
    container_name: share-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: .
    image: amazoncorretto:11
    container_name: share-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=share
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: share-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root